# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'renovate/**'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/typechecking.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/typechecking.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  workflow_call:
    secrets:
      MACOS_CSC_LINK:
        description: 'A token passed from the caller workflow'
        required: true
      MACOS_CSC_KEY_PASSWORD:
        description: 'A token passed from the caller workflow'
        required: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typechecking:
    uses: ./.github/workflows/typechecking.yml
  tests:
    uses: ./.github/workflows/tests.yml
  draft_release:
    permissions:
      contents: write # Allows this job to create releases
    with:
      dry-run: ${{ github.event_name != 'push' || github.ref_name != 'main' }}
    needs: [ typechecking, tests ]
    uses: ./.github/workflows/release.yml
    secrets:
      MACOS_CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}
      MACOS_CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}
