name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        placeholder: '1.0.0'
        pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
        default: ''
      os:
        description: 'Operating system'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - windows-latest
          - macos-latest

defaults:
  run:
    shell: 'bash'

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ${{ github.event.inputs.os == 'all' && 'windows-latest' || github.event.inputs.os }}
          - os: ${{ github.event.inputs.os == 'all' && 'macos-latest' || '' }}
        exclude:
          - os: ''

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run build
        env:
          MODE: production

      - name: Compile artifacts and upload them to GitHub release
        # I use this action because it is capable of retrying multiple times if there are any issues with the distribution server
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: 'bash'
          # Due to this issue https://github.com/electron-userland/electron-builder/issues/6411 the build with npx when rebuilding native dependencies hangs forever
          # see https://github.com/cawa-93/vite-electron-builder/pull/953
          command: ./node_modules/.bin/electron-builder --config electron-builder.yml -c.extraMetadata.version=${{ github.event.inputs.version }} --publish always
        env:
          # Code Signing params
          # See https://www.electron.build/code-signing
          CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}
          # Notarization params
          # See https://www.electron.build/configuration/mac#NotarizeNotaryOptions
          APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
          APPLE_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          # Publishing artifacts
          GH_TOKEN: ${{ secrets.github_token }} # GitHub token, automatically provided (No need to define this secret in the repo settings)

      - name: Sign Windows Build (exe)
        uses: sslcom/esigner-codesign@develop
        if: ${{ github.ref == 'refs/heads/main' && matrix.os == 'windows-latest' }}
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.WINDOWS_CREDENTIAL_ID_SIGNER }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: "${{ env.GITHUB_WORKSPACE }}/dist/Decentraland Launcher-win-x64.exe"
          output_path: "${{ env.GITHUB_WORKSPACE }}/dist/signed"
          malware_block: false
          environment_name: PROD

      - name: Replace signed exe
        if: ${{ github.ref == 'refs/heads/main' && matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          Copy-Item -Path "${env:GITHUB_WORKSPACE}\dist\signed\Decentraland Launcher-win-x64.exe" -Destination "${env:GITHUB_WORKSPACE}\dist\Decentraland Launcher-win-x64.exe" -Force
