name: Release
on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean
    secrets:
      MACOS_CSC_LINK:
        description: 'Certificate to sign dmg file'
        required: true
      MACOS_CSC_KEY_PASSWORD:
        description: 'Password to decrypt the certificate file'
        required: true
      MACOS_NOTARIZATION_APPLE_ID:
        description: 'Apple ID used for notarization'
        required: true
      MACOS_NOTARIZATION_TEAM_ID:
        description: 'Team ID used for notarization'
        required: true
      MACOS_NOTARIZATION_PWD:
        description: 'Password used for notarization'
        required: true
      ES_USERNAME:
        description: 'Username to sign exe file'
        required: true
      ES_PASSWORD:
        description: 'Password to sign the exe file'
        required: true
      WINDOWS_CREDENTIAL_ID_SIGNER:
        description: 'Certificate to sign the exe file'
        required: true
      ES_TOTP_SECRET:
        description: 'Password to decrypt the certificate file'
        required: true

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: 'bash'


jobs:
  draft_release:

    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        config:
          - os: macos-latest-large
            arch: x64
          # - os: macos-latest
          #   arch: arm64
          - os: windows-latest
            arch: x64

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run build

      - name: Generate Release Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          version_format: "${major}.${minor}.${patch}${{ GITHUB_REF == 'refs/heads/main' && '' || '-${increment}' }}"
          major_pattern: "/^(major|breaking).+/"
          minor_pattern: "/^(minor|feat).+/"
          bump_each_commit: false
          bump_each_commit_patch_pattern: "/^(patch|fix).+/"
          search_commit_body: true
          user_format_type: "json"

      - name: Compile artifacts ${{ inputs.dry-run && '' || 'and upload them to github release' }}
        # I use this action because it is capable of retrying multiple times if there are any issues with the distribution server
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: 'bash'
          # Due to this issue https://github.com/electron-userland/electron-builder/issues/6411 the build with npx when rebuilding native dependencies hangs forever
          # see https://github.com/cawa-93/vite-electron-builder/pull/953
          command: ./node_modules/.bin/electron-builder --config electron-builder.yml -c.extraMetadata.version=${{ steps.version.outputs.version }} --publish ${{ inputs.dry-run && 'never' || 'always' }}
        env:
          # Code Signing params
          # See https://www.electron.build/code-signing
          CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}
          # Publishing artifacts
          GH_TOKEN: ${{ secrets.github_token }} # GitHub token, automatically provided (No need to define this secret in the repo settings)

      - name: Notarize MacOS (dmg)
        if: ${{github.ref == 'refs/heads/main' && startsWith(matrix.config.os, 'macos-latest') && !inputs.dry-run}}
        env:
          MACOS_NOTARIZATION_APPLE_ID: ${{secrets.MACOS_NOTARIZATION_APPLE_ID}}
          MACOS_NOTARIZATION_TEAM_ID: ${{secrets.MACOS_NOTARIZATION_TEAM_ID}}
          MACOS_NOTARIZATION_PWD: ${{secrets.MACOS_NOTARIZATION_PWD}}
        run: |
          # Store the notarization credentials to prevent the UI password dialog for blocking the CI
          echo "Create keychain profile"
          xcrun notarytool store-credentials "notary-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"

          # Send the notarization request to the Apple's Notarization service and wait for the result.
          echo "Notarize app"
          xcrun notarytool submit "dist/Decentraland Launcher-mac-x64.dmg" --keychain-profile "notary-profile" --wait
          xcrun notarytool submit "dist/Decentraland Launcher-mac-arm64.dmg" --keychain-profile "notary-profile" --wait

          # Attach the staple to the executable, this allow the app to be validated by macOS
          # even when an internet connection is not available.
          echo "Attach staple"
          xcrun stapler staple "dist/Decentraland Launcher-mac-x64.dmg"
          xcrun stapler staple "dist/Decentraland Launcher-mac-arm64.dmg"

          # Validate the staple attached to the executable.
          echo "Validate staple"
          xcrun stapler validate "dist/Decentraland Launcher-mac-x64.dmg"
          xcrun stapler validate "dist/Decentraland Launcher-mac-arm64.dmg"

      - name: Sign Windows Build (exe)
        uses: sslcom/esigner-codesign@develop
        if: ${{github.ref == 'refs/heads/main' && matrix.config.os == 'windows-latest' && !inputs.dry-run}}
        with:
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.WINDOWS_CREDENTIAL_ID_SIGNER }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${GITHUB_WORKSPACE}/dist/Decentraland Launcher-win-${{ matrix.config.arch }}.exe
          output_path: ${GITHUB_WORKSPACE}/dist/signed
          malware_block: false
          environment_name: PROD

      - name: Replace signed exe
        if: ${{github.ref == 'refs/heads/main' && matrix.config.os == 'windows-latest' && !inputs.dry-run}}
        shell: pwsh
        run: |
          Copy-Item -Path "${env:GITHUB_WORKSPACE}\dist\signed\Decentraland Launcher-win-${{ matrix.config.arch }}.exe" -Destination "${env:GITHUB_WORKSPACE}\dist\Decentraland Launcher-win-${{ matrix.config.arch }}.exe" -Force
